"""Add username column to users table

Revision ID: b86b5a330a9a
Revises: f5c9ad53a34b
Create Date: 2025-07-23 11:51:35.487830

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b86b5a330a9a"
down_revision: Union[str, Sequence[str], None] = "f5c9ad53a34b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
